"""自进化链路的**稳定审计 reason code**（不依赖中文自由文本）。

规划文档《R20 自进化系统正确优化实施规格》§8.3：凡是要落审计/告警的拒绝、
降级、边界事件，都必须有一个**机器可读的常量**，中文文案只作人类附注。
这样 grep 日志能直接定位事件类型，前端告警也能按 code 分派，
不必去正则匹配一段随时会被改写的说明文字。

纯常量模块：无副作用、无 import、无 I/O。
"""
from __future__ import annotations

MEMORY_BASELINE_MISMATCH = "MEMORY_BASELINE_MISMATCH"
MEMORY_PUBLISH_REJECTED = "MEMORY_PUBLISH_REJECTED"
SNAPSHOT_TIME_UNVERIFIED = "SNAPSHOT_TIME_UNVERIFIED"
SNAPSHOT_REUSED = "SNAPSHOT_REUSED"
RULE_PROPOSAL_OBSERVATION_ONLY = "RULE_PROPOSAL_OBSERVATION_ONLY"
RULE_PROPOSAL_REQUIRES_APPROVAL = "RULE_PROPOSAL_REQUIRES_APPROVAL"
HARD_RULE_BLOCKED = "HARD_RULE_BLOCKED"
ASSET_MULTIPLIER_APPLIED = "ASSET_MULTIPLIER_APPLIED"
ASSET_MULTIPLIER_EXPIRED = "ASSET_MULTIPLIER_EXPIRED"
ASSET_MULTIPLIER_INVALID = "ASSET_MULTIPLIER_INVALID"

REASON_CODES = (
    MEMORY_BASELINE_MISMATCH,
    MEMORY_PUBLISH_REJECTED,
    SNAPSHOT_TIME_UNVERIFIED,
    SNAPSHOT_REUSED,
    RULE_PROPOSAL_OBSERVATION_ONLY,
    RULE_PROPOSAL_REQUIRES_APPROVAL,
    HARD_RULE_BLOCKED,
    ASSET_MULTIPLIER_APPLIED,
    ASSET_MULTIPLIER_EXPIRED,
    ASSET_MULTIPLIER_INVALID,
)
